/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export { }

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertMessage: typeof import('./src/components/alertMessage/index.vue')['default']
    Alipay: typeof import('./src/components/icons/Alipay.vue')['default']
    Dingding: typeof import('./src/components/icons/Dingding.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    Logo: typeof import('./src/components/icons/Logo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowPassword: typeof import('./src/components/icons/ShowPassword.vue')['default']
    Swiper: typeof import('./src/components/Swiper/index.vue')['default']
    Weixin: typeof import('./src/components/icons/Weixin.vue')['default']
  }
}
